---
- name: Configure banner
  hosts: routers
  remote_user: admin
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Configure banner from file
      cisco.ios.ios_banner:
        banner: motd
        text: "{{ lookup('file', './banner.txt') }}"  # Use unix formatted text files (LF not CRLF) to avoid idempotency issues.
        state: present
